package typeclasses.example

import java.util.Date

import typeclasses.example.JSONApi.{JSONArray, JSONNumber, JSONObject, JSONString}

/*
 * This Scala source file was generated by the Gradle 'init' task.
 */

object JSONSerializationApp extends App {

  /*
    1. Intermediate data types: Int, String, Date
    2. Type class for conversion to intermediate data types
    3. Serialize to JSON
   */

  val data = JSONObject(Map(
    "user" -> JSONString("Daniel"),
    "posts" -> JSONArray(List(JSONString("Scala Rocks"), JSONNumber(453)))
  ))

  println(data.stringify)



  val now = new Date(System.currentTimeMillis())
  val john = User("John", 34, "john@example.com")
  val feed = Feed(john, List(
    Post("hello, I'm John.", now),
    Post("Good Bye, John.", now)
  ))

  import JSONManager._

  println(feed.toJSON.stringify)


}



